name: Get Gallery Images

on:
  schedule:
    # At 00:00 on Sunday.
    - cron: '0 0 * * 0'

  workflow_dispatch:

jobs:
  get-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install packages
        run: npm run action:install

      - name: Create .env
        run: |
          touch .action/.env
          echo DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }} >> .action/.env

      - name: Run TS Action
        run: npm run action:start

      - name: Check for modified files
        id: git-check
        run: echo "modified=$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")" >> $GITHUB_OUTPUT
      - name: Commit latest images
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add src/galleryImages.json
          git commit -m "New Images"
          git push
